// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatpb/chat.proto

package chatpb // import "./chatpb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User1 struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Send                 string   `protobuf:"bytes,2,opt,name=send,proto3" json:"send,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User1) Reset()         { *m = User1{} }
func (m *User1) String() string { return proto.CompactTextString(m) }
func (*User1) ProtoMessage()    {}
func (*User1) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_238e5538ae8bddc7, []int{0}
}
func (m *User1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User1.Unmarshal(m, b)
}
func (m *User1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User1.Marshal(b, m, deterministic)
}
func (dst *User1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User1.Merge(dst, src)
}
func (m *User1) XXX_Size() int {
	return xxx_messageInfo_User1.Size(m)
}
func (m *User1) XXX_DiscardUnknown() {
	xxx_messageInfo_User1.DiscardUnknown(m)
}

var xxx_messageInfo_User1 proto.InternalMessageInfo

func (m *User1) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User1) GetSend() string {
	if m != nil {
		return m.Send
	}
	return ""
}

type User2 struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Send                 string   `protobuf:"bytes,2,opt,name=send,proto3" json:"send,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User2) Reset()         { *m = User2{} }
func (m *User2) String() string { return proto.CompactTextString(m) }
func (*User2) ProtoMessage()    {}
func (*User2) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_238e5538ae8bddc7, []int{1}
}
func (m *User2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User2.Unmarshal(m, b)
}
func (m *User2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User2.Marshal(b, m, deterministic)
}
func (dst *User2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User2.Merge(dst, src)
}
func (m *User2) XXX_Size() int {
	return xxx_messageInfo_User2.Size(m)
}
func (m *User2) XXX_DiscardUnknown() {
	xxx_messageInfo_User2.DiscardUnknown(m)
}

var xxx_messageInfo_User2 proto.InternalMessageInfo

func (m *User2) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User2) GetSend() string {
	if m != nil {
		return m.Send
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_238e5538ae8bddc7, []int{2}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*User1)(nil), "chatpb.User1")
	proto.RegisterType((*User2)(nil), "chatpb.User2")
	proto.RegisterType((*Token)(nil), "chatpb.Token")
}

func init() { proto.RegisterFile("chatpb/chat.proto", fileDescriptor_chat_238e5538ae8bddc7) }

var fileDescriptor_chat_238e5538ae8bddc7 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xce, 0x48, 0x2c,
	0x29, 0x48, 0xd2, 0x07, 0x51, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x21, 0x25,
	0x6d, 0x2e, 0xd6, 0xd0, 0xe2, 0xd4, 0x22, 0x43, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xd6, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x21, 0x2e, 0x96, 0xe2, 0xd4, 0xbc, 0x14,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b, 0xa6, 0xd8, 0x88, 0x28, 0xc5, 0xb2, 0x5c,
	0xac, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x42, 0x22, 0x50, 0x86, 0x04, 0x33, 0x58, 0x16, 0xc2, 0x31,
	0x4a, 0xe7, 0xe2, 0x76, 0xce, 0x48, 0x2c, 0x09, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xd2,
	0xe6, 0xe2, 0x04, 0x71, 0x21, 0x6e, 0xe1, 0xd5, 0x83, 0xb8, 0x4e, 0x0f, 0xcc, 0x95, 0x82, 0x73,
	0xc1, 0x3a, 0x95, 0x18, 0x90, 0x15, 0x1b, 0xa1, 0x2a, 0x36, 0xc2, 0x50, 0xec, 0xc4, 0x15, 0xc5,
	0xa1, 0xa7, 0x0f, 0x11, 0x4b, 0x62, 0x03, 0x7b, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc9,
	0xfc, 0xc8, 0x90, 0x11, 0x01, 0x00, 0x00,
}
