// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatpb/chat.proto

package chatpb // import "./chatpb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User1 struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Send                 string   `protobuf:"bytes,2,opt,name=send,proto3" json:"send,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User1) Reset()         { *m = User1{} }
func (m *User1) String() string { return proto.CompactTextString(m) }
func (*User1) ProtoMessage()    {}
func (*User1) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1523f64fdedcdc1a, []int{0}
}
func (m *User1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User1.Unmarshal(m, b)
}
func (m *User1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User1.Marshal(b, m, deterministic)
}
func (dst *User1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User1.Merge(dst, src)
}
func (m *User1) XXX_Size() int {
	return xxx_messageInfo_User1.Size(m)
}
func (m *User1) XXX_DiscardUnknown() {
	xxx_messageInfo_User1.DiscardUnknown(m)
}

var xxx_messageInfo_User1 proto.InternalMessageInfo

func (m *User1) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User1) GetSend() string {
	if m != nil {
		return m.Send
	}
	return ""
}

type User2 struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Send                 string   `protobuf:"bytes,2,opt,name=send,proto3" json:"send,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User2) Reset()         { *m = User2{} }
func (m *User2) String() string { return proto.CompactTextString(m) }
func (*User2) ProtoMessage()    {}
func (*User2) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1523f64fdedcdc1a, []int{1}
}
func (m *User2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User2.Unmarshal(m, b)
}
func (m *User2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User2.Marshal(b, m, deterministic)
}
func (dst *User2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User2.Merge(dst, src)
}
func (m *User2) XXX_Size() int {
	return xxx_messageInfo_User2.Size(m)
}
func (m *User2) XXX_DiscardUnknown() {
	xxx_messageInfo_User2.DiscardUnknown(m)
}

var xxx_messageInfo_User2 proto.InternalMessageInfo

func (m *User2) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User2) GetSend() string {
	if m != nil {
		return m.Send
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1523f64fdedcdc1a, []int{2}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Message struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Sender               string   `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             string   `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1523f64fdedcdc1a, []int{3}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Message) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func init() {
	proto.RegisterType((*User1)(nil), "chatpb.User1")
	proto.RegisterType((*User2)(nil), "chatpb.User2")
	proto.RegisterType((*Token)(nil), "chatpb.Token")
	proto.RegisterType((*Message)(nil), "chatpb.Message")
}

func init() { proto.RegisterFile("chatpb/chat.proto", fileDescriptor_chat_1523f64fdedcdc1a) }

var fileDescriptor_chat_1523f64fdedcdc1a = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xce, 0x48, 0x2c,
	0x29, 0x48, 0xd2, 0x07, 0x51, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x21, 0x25,
	0x6d, 0x2e, 0xd6, 0xd0, 0xe2, 0xd4, 0x22, 0x43, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xd6, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x21, 0x2e, 0x96, 0xe2, 0xd4, 0xbc, 0x14,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b, 0xa6, 0xd8, 0x88, 0x28, 0xc5, 0xb2, 0x5c,
	0xac, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x42, 0x22, 0x50, 0x86, 0x04, 0x33, 0x58, 0x16, 0xc2, 0x51,
	0x0a, 0xe4, 0x62, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x05, 0xe9, 0x2e, 0x49, 0xad, 0x28,
	0x01, 0x9b, 0xc7, 0x19, 0x04, 0x66, 0x0b, 0x89, 0x71, 0xb1, 0x81, 0x4c, 0x49, 0x2d, 0x82, 0x9a,
	0x09, 0xe5, 0x09, 0x49, 0x71, 0x71, 0x14, 0xa5, 0x26, 0xa7, 0x66, 0x96, 0xa5, 0x16, 0x41, 0xcd,
	0x83, 0xf3, 0x8d, 0x66, 0x31, 0x72, 0x71, 0x3b, 0x67, 0x24, 0x96, 0x04, 0xa7, 0x16, 0x95, 0x65,
	0x26, 0xa7, 0x0a, 0x69, 0x73, 0x71, 0x82, 0xb8, 0x10, 0xff, 0xf1, 0xea, 0x41, 0x7c, 0xac, 0x07,
	0xe6, 0x4a, 0xc1, 0xb9, 0x10, 0xd7, 0x30, 0x20, 0x2b, 0x36, 0x42, 0x55, 0x6c, 0x84, 0xa9, 0xd8,
	0x90, 0x8b, 0x3b, 0x38, 0x35, 0x2f, 0x05, 0xe6, 0x01, 0x7e, 0x98, 0x3c, 0x54, 0x40, 0x0a, 0x5d,
	0x40, 0x89, 0xc1, 0x89, 0x2b, 0x8a, 0x43, 0x4f, 0x1f, 0x22, 0x9a, 0xc4, 0x06, 0x8e, 0x03, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x3b, 0x27, 0x3d, 0x98, 0x01, 0x00, 0x00,
}
